import logging
import re
import os
import json
from typing import List, Optional, Dict, Any
from datetime import datetime

from src.entity.enhanced_states import GeneratedCodeFile

logger = logging.getLogger(__name__)


class CodeManager:
    """代码管理器，负责整理、保存和执行生成的Python代码"""
    
    def __init__(self, workspace_directory: str):
        self.workspace_directory = workspace_directory
        self.code_directory = os.path.join(workspace_directory, "generated_scripts")
        os.makedirs(self.code_directory, exist_ok=True)
    
    def extract_python_code(self, content: str) -> List[str]:
        """从文本中提取Python代码块"""
        code_blocks = []
        
        # 如果是字典或列表，先转换为字符串
        if isinstance(content, (dict, list)):
            content = json.dumps(content, ensure_ascii=False, indent=2)
        
        # 首先尝试从嵌套的JSON结构中提取"code"字段
        try:
            # 尝试解析为JSON
            data = json.loads(content)
            # 递归提取所有可能的代码
            def extract_code_recursive(obj):
                if isinstance(obj, dict):
                    for key, value in obj.items():
                        if key == 'code' and isinstance(value, str):
                            code_blocks.append(value.strip())
                        elif key == 'tool_parameters' and isinstance(value, dict):
                            if 'code' in value and isinstance(value['code'], str):
                                code_blocks.append(value['code'].strip())
                        else:
                            extract_code_recursive(value)
                elif isinstance(obj, list):
                    for item in obj:
                        extract_code_recursive(item)
            extract_code_recursive(data)
        except:
            pass
        
        # 匹配```python ... ```格式的代码块
        python_pattern = r'```python\s*([\s\S]*?)\s*```'
        matches = re.finditer(python_pattern, content)
        for match in matches:
            code = match.group(1).strip()
            if code and code not in code_blocks:
                code_blocks.append(code)
        
        # 匹配``` ... ```格式并判断是否为Python代码
        generic_pattern = r'```\s*([\s\S]*?)\s*```'
        matches = re.finditer(generic_pattern, content)
        for match in matches:
            code = match.group(1).strip()
            # 检查是否是Python代码特征
            if code and code not in code_blocks:
                if (('import ' in code or 'def ' in code or 'class ' in code or 
                     'pandas' in code or 'numpy' in code or 'plt.' in code or
                     'pd.' in code or 'np.' in code)):
                    code_blocks.append(code)
        
        return code_blocks
    
    def clean_and_format_code(self, code: str) -> str:
        """清理和格式化Python代码"""
        # 移除多余的空行
        lines = code.split('\n')
        cleaned_lines = []
        last_line_empty = False
        
        for line in lines:
            stripped = line.rstrip()
            if stripped == '':
                if not last_line_empty:
                    cleaned_lines.append('')
                    last_line_empty = True
            else:
                cleaned_lines.append(stripped)
                last_line_empty = False
        
        # 确保代码以空行结尾
        if cleaned_lines and cleaned_lines[-1] != '':
            cleaned_lines.append('')
        
        return '\n'.join(cleaned_lines)
    
    def add_script_header(self, code: str, script_name: str, description: str = "") -> str:
        """为代码添加脚本头部信息"""
        header = f'''"""
{script_name}
{description}

Generated by Data Agent System
Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

'''
        return header + code
    
    def create_code_file(
        self, 
        code: str, 
        filename_prefix: str = "script",
        description: str = ""
    ) -> GeneratedCodeFile:
        """创建并保存Python代码文件"""
        # 清理代码
        cleaned_code = self.clean_and_format_code(code)
        
        # 生成唯一文件名
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{filename_prefix}_{timestamp}.py"
        
        # 添加脚本头部
        code_with_header = self.add_script_header(cleaned_code, filename, description)
        
        # 保存文件
        code_file = GeneratedCodeFile(
            filename=filename,
            code_content=code_with_header
        )
        file_path = code_file.save_to_file(self.code_directory)
        
        logger.info(f"Created code file: {file_path}")
        return code_file
    
    def create_code_files_from_content(
        self, 
        content: str,
        filename_prefix: str = "analysis"
    ) -> List[GeneratedCodeFile]:
        """从内容中提取并创建多个代码文件"""
        code_blocks = self.extract_python_code(content)
        code_files = []
        
        for i, code in enumerate(code_blocks):
            prefix = f"{filename_prefix}_{i+1}" if len(code_blocks) > 1 else filename_prefix
            code_file = self.create_code_file(
                code=code,
                filename_prefix=prefix,
                description=f"Extracted code block {i+1}"
            )
            code_files.append(code_file)
        
        return code_files
    
    def list_code_files(self) -> List[str]:
        """列出所有生成的代码文件"""
        if not os.path.exists(self.code_directory):
            return []
        
        files = []
        for filename in os.listdir(self.code_directory):
            if filename.endswith('.py'):
                files.append(filename)
        
        return sorted(files, reverse=True)
    
    def get_code_file_content(self, filename: str) -> Optional[str]:
        """获取代码文件内容"""
        file_path = os.path.join(self.code_directory, filename)
        if os.path.exists(file_path):
            with open(file_path, 'r', encoding='utf-8') as f:
                return f.read()
        return None
    
    def delete_code_file(self, filename: str) -> bool:
        """删除代码文件"""
        file_path = os.path.join(self.code_directory, filename)
        if os.path.exists(file_path):
            os.remove(file_path)
            logger.info(f"Deleted code file: {file_path}")
            return True
        return False


def execute_python_sandbox(
    code: str, 
    workspace_directory: str,
    timeout_seconds: int = 60
) -> Dict[str, Any]:
    """
    在沙盒环境中执行Python代码
    
    注意：这是一个简化版本，实际生产环境应该使用更安全的沙盒机制
    """
    import subprocess
    import tempfile
    
    result = {
        "success": False,
        "output": "",
        "error": "",
        "execution_time": 0
    }
    
    # 创建临时脚本文件
    with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False, encoding='utf-8') as f:
        f.write(code)
        temp_script_path = f.name
    
    try:
        start_time = datetime.now()
        
        # 设置工作目录
        env = os.environ.copy()
        env['PYTHONPATH'] = workspace_directory
        
        # 执行脚本
        process = subprocess.Popen(
            ['python', temp_script_path],
            cwd=workspace_directory,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout_seconds
        )
        
        stdout, stderr = process.communicate()
        
        end_time = datetime.now()
        execution_time = (end_time - start_time).total_seconds()
        
        result["output"] = stdout
        result["error"] = stderr
        result["execution_time"] = execution_time
        result["success"] = process.returncode == 0
        
    except subprocess.TimeoutExpired:
        result["error"] = f"Execution timed out after {timeout_seconds} seconds"
        process.kill()
    except Exception as e:
        result["error"] = str(e)
    finally:
        # 清理临时文件
        try:
            os.unlink(temp_script_path)
        except:
            pass
    
    return result
